language: node_js
node_js:
- '11'
branches:
  only:
  - master
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
script:
  - ng lint
  - ng build --prod --base-href https://hacking-style.web.app/
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
