language: node_js
node_js:
- '10'
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng lint
- ng build --prod --base-href https://hacking-style.web.app/

deploy:
  provider: firebase
  token: Qeign7Ni5twJO7iobZ9XWph70KmMf1AjlTtbbHwg8KaZQx+Qh8WqSr8FS88by9nj5y8tNJZjV1s8HErTJcGNAokftY91j7IaxJw1GKLIHWsOEiUPDHsBNZKtj1xt0OM9U5S+K27IwUpHNibNDZ0933qA0fqGC8GauWgfJ7ffd6mojK8rlOlcMT+O7F04pmMByd1eX1q+pa9vX6kCBtqdWAqLHjSnKq8CPMPqzsO8pcTMobXZH7O6+Apt4GdQsWk6gYi7hQLqic2BzElZeVXKsUsZkLk9obVGBONNmtgDI8Oe7Nf5O2MOp2GPvzwMJQwGxe3rz2aRqc15opicXn7FWnRmvKqjtAw98IMbxRpUsMzH66OZ5W+afJ+Nc4kDhzLX4OIfE/TsDXezEa/WaIQxH444NjTwxqbrpB3/W7wqpP/d5Tm83Bq6Z3wKlfH9oSy+gh9jqbXOUZEPPBPgR7YCkCECpuAZ3JdpBOovAfrxdcGJF8o+UHtGYAUQm/qj9HCIPfIJ1vUh4eb4xINgrOO2XOvdXMxFEf3gkV6tctv3745T0CjKApaZKs6DZWAjZxY/4xAo2FtkKG7dGNO5f4bJ4G9YNKg7vcpNh16gdKGegZzc2LchTIQ7cRLQjlN+7hCa5RIxPtT0sDOoj1B9ZtzxS6kBsIcgF9iRaHeaZmDr//k=
